export enum AutomationType {
  LEAD_NURTURING = "LEAD_NURTURING",
  WELCOME_SERIES = "WELCOME_SERIES",
  FOLLOW_UP = "FOLLOW_UP",
  ABANDONED_CART = "ABANDONED_CART",
  BIRTHDAY = "BIRTHDAY",
  ANNIVERSARY = "ANNIVERSARY",
  RE_ENGAGEMENT = "RE_ENGAGEMENT",
  ONBOARDING = "ONBOARDING",
  FEEDBACK = "FEEDBACK",
  RETENTION = "RETENTION"
}
