export enum CampaignCategory {
  PROMOTIONAL = "PROMOTIONAL",
  EDUCATIONAL = "EDUCATIONAL",
  FOLLOW_UP = "FOLLOW_UP",
  WELCOME = "WELCOME",
  NEWSLETTER = "NEWSLETTER",
  ANNOUNCEMENT = "ANNOUNCEMENT",
  REMINDER = "REMINDER",
  SURVEY = "SURVEY",
  EVENT = "EVENT",
  PRODUCT_LAUNCH = "PRODUCT_LAUNCH"
}
