export enum CommunicationChannel {
  EMAIL = 'EMAIL',
  WHATSAPP = 'WHATSAPP',
  SMS = 'SMS',
  PHONE_CALL = 'PHONE_CALL',
  TELEGRAM = 'TELEGRAM',
  FACEBOOK_MESSENGER = 'FACEBOOK_MESSENGER',
  INSTAGRAM = 'INSTAGRAM',
  LINKEDIN = 'LINKEDIN',
  TWITTER = 'TWITTER',
  CHAT_WIDGET = 'CHAT_WIDGET',
  OTHER = 'OTHER'
}
