export enum InteractionTag {
    SALES = "SALES",
    SUPPORT = "SUPPORT",
    MARKETING = "MARKETING",
    ONBOARDING = "ONBOARDING",
    COMPLAINT = "COMPLAINT",
    FEEDBACK = "FEEDBACK",
    TECHNICAL = "TECHNICAL",
    BILLING = "BILLING",
    PARTNERSHIP = "PARTNERSHIP",
    TRAINING = "TRAINING",
    MAINTENANCE = "MAINTENANCE",
    UPSELL = "UPSELL",
    RETENTION = "RETENTION",
    SURVEY = "SURVEY",
    EVENT = "EVENT",
    FOLLOW_UP = "FOLLOW_UP"
}

