export enum OpportunityCloseReason {
    BUDGET_CUT = "BUDGET_CUT",
    COMPETITOR_WON = "COMPETITOR_WON",
    NO_DECISION = "NO_DECISION",
    NOT_QUALIFIED = "NOT_QUALIFIED",
    PRICE_TOO_HIGH = "PRICE_TOO_HIGH",
    TIMING_NOT_RIGHT = "TIMING_NOT_RIGHT",
    TECHNICAL_ISSUES = "TECHNICAL_ISSUES",
    CUSTOMER_CHANGED_MIND = "CUSTOMER_CHANGED_MIND",
    OTHER = "OTHER"
}
