export enum RecipientStatus {
  PENDING = "PENDING",
  SENT = "SENT",
  DELIVERED = "DELIVERED",
  OPENED = "OPENED",
  CLICKED = "CLICKED",
  REPLIED = "REPLIED",
  BOUNCED = "BOUNCED",
  UNSUBSCRIBED = "UNSUBSCRIBED",
  FAILED = "FAILED"
}
